### ISSUE TITLE
Add Quiz App

### ISSUE THREAD

**Issue by PRERNA-CHOUDHARY** [nischalgautam2/WebDevProjects#16]
I would like to add a quiz app(HTML, CSS ,JS) to this repository,@nichalgautam2  Kindly assign this to me under hacktoberfest, hacktoberfest-accepted label.

**Comment by geetika001** [comment]
Please assign this to me.I'll be making an interesting quiz webapp using HTML,CSS and JS(considering your topic of interest as well).Requesting you to consider for hacktoberfest.
